name: Archive Release
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        path: 'extension'
        filename: 'extension.zip'
    - name: Upload Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "extension.zip"
        tag: "latest"
        token: ${{ secrets.GITHUB_TOKEN }}
